sudo: required
services:
- docker
install:
- docker build -t $BUILDING .
script:
- docker run --rm -it $BUILDING npm test
after_success:
- docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
- |
  if [ -n "$TRAVIS_TAG" ]; then
    docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_TAG;
    docker push $DOCKER_IMAGE:$TRAVIS_TAG;
  fi
- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker tag $BUILDING $DOCKER_IMAGE:$TRAVIS_BRANCH;
    docker push $DOCKER_IMAGE:$TRAVIS_BRANCH;
  fi
env:
  global:
  - DOCKER_IMAGE=idigbio/idb-portal
  - BUILDING=$DOCKER_IMAGE:$TRAVIS_COMMIT
notifications:
  slack:
    secure: "I81gfdzQkDwifE3OSmgfmseoTToRXECn9Cvkcfm5AStk7kUZ4vQYbgj+lSIABfz8G6K7X9KlIsbRSe2IOaBJAyBFbINN7u101/W8NyWieqPHPjnj7DJcldKQLSj/D8HotrKeeljrJMiGp4P60JefV7URBqlMqM4n9VWp4lH68d9uJ7IfHcElVwCHKKQShpggw5UYq1e4mwlfS3/wRaPJeMyPyDS6bYBMrl3s9yXdvxcbgrpo9TonQ5lvS8r2S1FFYWeSzN7o3advLYKeGriol6YR+N0trSKFj1dt21HYGtTlTtqMo6OLElidHHb9zNZEqhHNOTJbz7QxXbQ3A/tvtQnnV3NTsDEY7OcbEuArWaaHvw+5hFFnZiN0V3xqiYHBPotMfZ1TMEJZhXE5rd4uFOSz2O9wV2bjw0Zq66Q7aj2DSuCi8cxpJ31IGj3Chs3EtD9XsXJsHSEtT5rahmL9HmAIm3Vef1J8E+MINAQT2uN0hgYBGNtEd9sXo229rWRcXFke/jnObaA0hISNJQLsPG9lvSsmMHvbUvrDlJKRIMfpbSc1eAe01FMC4rZUVAS6Xp36qdVB55f+aOBBrysRKx4O9dDj0TmEacGeREV79E59VkDQC5/ZIXPq6r7Xs+9ZzyAS28b3vCvM8MJO1oiuBXijFO1kfdmKaqIqxY0dEek="
